### ISSUE TITLE
About still mentions CodePlex

### ISSUE THREAD

**Issue by tomkerkhove** [dotnet/home#104]
About still mentions CodePlex which is now in archive mode.

![image](https://user-images.githubusercontent.com/4345663/42086259-e0b7d008-7b92-11e8-96c9-02ee61ddc457.png)

Is this something that I can PR?

**Comment by jnm2** [comment]
https://github.com/dotnet/dotnetfoundation-website?

**Comment by jnm2** [comment]
https://github.com/dotnet/dotnetfoundation-website/blob/master/src/Pages/About.cshtml#L15?
