### ISSUE TITLE
Shown version is very confusing

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/home#31]
Hi,

I don't know exactly in which repo I should post this issue, I hope you can direct it to the right place.
I use VS 2015 Update 1 RC and if I create a new Web -> Class library project with .NET Framework 4.6 my reference section shows ".NET Framework 4.5.1" and the new ".NET Platform 5.4".
But why ".NET Framework 4.5.1", this is in no way clear and confusing I think.
I don't know the reason but even if it is because .NET 4.6 is backward compatible to .NET 4.5.1, shown should anyway the Framework I choose on "New project".

Kind regards

**Comment by Petermarcu** [comment]
I see this is a really old issue but I'll try to respond. The version that Visual Studio defaults to for libraries is the version that we believe most user will have on their machines. There were a lot of things that weren't finished in the Web projects for VS 2015 so some of it may be that as well. I'm going to close this issue but if there is still any weirdness in the tooling that releases with the next release of Visual Studio or the .NET Core tooling built on top of it, please get back in touch.
