### ISSUE TITLE
Location of Microsoft.Cci

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/home#43]
Hello!

I've found that Microsoft.Cci is still active in development as per the NuGet feed:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.Cci

Unfortunately, I wasn't able to find the repository where the sources are maintained and would very much appricate information to this regard.

Many thanks, Michael

**Comment by jkotas** [comment]
cc @nguerrera

**Comment by MichaelKetting** [comment]
@jkotas Thanks for forwarding this!
Is there a better place to ask this question? I've looked at the corefx repo and several others that looked at least remotely promising and there wasn't anything obvious in regards to Microsoft.Cci.

**Comment by nguerrera** [comment]
I apologize for the delay in responding to this. We will have more information available very shortly.

cc @michaelcfanning

**Comment by MichaelKetting** [comment]
@nguerrera Thank you very much!

**Comment by nguerrera** [comment]
We have now published https://github.com/microsoft/cci

Please make note of the README there for the level of investment to expect. Also, there is not yet an automated build that publishes from that repo to nuget. The source there is effectively newer than the package used by corefx buildtools. We will be working to have a nuget package that builds from the new repo and moving the corefx buildtools over to it. However, I do not have an ETA yet for that.

**Comment by MichaelKetting** [comment]
Thanks for publishing those and the readme explaining the status. I can't speak for the rest of the community, but for me the most important thing is to have a CCI that works with the latest PDBs (C#6 introduced new metadata types that crashed v1.0.13 but I can see that eventuelly an investment into Reflection.Metadata and Cecil might be advisable.

**Comment by Petermarcu** [comment]
I am going to close this issue as it appears to have been resolved by the open sourcing of cci at https://github.com/microsoft/cci

**Comment by MichaelKetting** [comment]
Yes, thank you!
