### ISSUE TITLE
Request for information on how Microsoft plans to make c# the nr.1 language

### ISSUE THREAD

**Issue by Meai1** [dotnet/home#47]
Realistically will csharp ever reach the #1 spot of programming languages? Is it even a goal?
I have this nagging feeling that microsoft doesn't even want it to be the #1
Are you okay with #2 or even #5?
I don't work every day as hard as I possibly can just to wake up and feel like a chump who uses a second class ranked language.

These are the facts: 
http://www.tiobe.com/tiobe-index/

![problem](https://cloud.githubusercontent.com/assets/1112157/17269497/4992ea1a-564a-11e6-9424-add585040ee9.PNG)

c# is not just a community, it's a family and as such we should stick together and make it greater than ever before.
What I want to hear from Microsoft is a fight plan on how we are going to get to the top spot, what needs to be done and what we as a community can do to help to get there.
I also want an analysis from the managers and a statement, possibly an apology actually as to why exactly we are still not the number 1.

**Comment by svick** [comment]
> Realistically will csharp ever reach the # 1 spot of programming languages? Is it even a goal?

I don't think the goal of C# is to be everything for everyone.

Part of what Java is famous for are cross-platform GUI applications, C#/.Net does not try hard in that space.

C and C++ are mostly systems programming languages with manual/deterministic memory management, C# does not try to be that.

Python, PHP and JavaScript are dynamic languages, C# is not one.

>I don't work every day as hard as I possibly can just to wake up and feel like a chump who uses a second class ranked language.

Nobody is forcing you to use C#. If your criteria for what language you use is: "It has to be the number one language", then it seems you should use Java.

> These are the facts: http://www.tiobe.com/tiobe-index/

[The TIOBE index is a fairly crude ranking.](http://www.tiobe.com/tiobe-index/programming-languages-definition/) If anything, I would look at [the IEEE Spectrum ranking](http://spectrum.ieee.org/static/interactive-the-top-programming-languages-2016).

> I also want an analysis from the managers and a statement, possibly an apology actually as to why exactly we are still not the number 1. 

Apology? Huh? I don't understand. I don't think being the most popular language was ever the goal of C#, so there is nothing to apologize for. And with .Net Core and closer relationship of Microsoft with Xamarin and Unity, I think C# is on a good way to become more popular than ever.

**Comment by eyalsk** [comment]
@svick, @Meai1 

> Part of what Java is famous for are cross-platform GUI applications, C#/.Net does not try hard in that space.

It's not really related to the language but more the framework, Java got AWT as part of the JCL and some frameworks are building on top of that; others, create their own from the ground up.

Currently, as far as I understand the .NET Core team is trying to find a 2D library that will serve all their needs and this will also be the foundation for System.Drawing.

When it comes to 3D and DirectX alternative or really a WPF alternative I don't know but my guess is that once they will nail everything and the opportunity will be available for them they will create a cross-platform UI framework but it will take some time but that's just a hunch.

You can read more about it [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/glossary.md).

Let's not forget that Java is more mature than C# and their JCL was designed and implemented right from the start to be cross-platform whereas the .NET stack had to be revolutionized to be able to head in the same direction.

> C and C++ are mostly systems programming languages with manual/deterministic memory management, C# does not try to be that.

You're right C# will probably never have deterministic memory management but there are many other factors that make C/++ high on the list there.

C/++ is very mature, there are many, many solutions and codebases that were written in C/++, almost all if not all of OS support C and probably C++, the language is getting better, the STL is getting better so there's no reason to stop writing in C/++.

However, nothing prevents C# from being faster and better and allow us to have more control, there's a fairly good discussion about performance [here](https://github.com/dotnet/roslyn/issues/10378) though not everything is strictly related to memory.

> Python, PHP and JavaScript are dynamic languages, C# is not one.

I don't think that this is the reason that make people prefer these languages over C#.

Python is cross-platform, it is used in so many ways like research and math, it's provided with almost all Linux distros if not all of them, IT engineers are using it when a Bash script isn't good enough whereas when a Batch script won't do people on Windows will probably pick PowerShell over C#.

JavaScript like Python has a very clear path and it's used and run everywhere so it will probably get more and more love.

PHP is a syndrome! j/k.. but really the language isn't that amazing it's just that there's a huge community around it and this is the reason it's growing.

All in all to really push C# to the top, the C# team and the community need to blog more about it, to have more videos, maybe even having conferences and stuff like this as well as writing quality stuff with it and publish it as open source and finally C# needs to have a clear roadmap for **where** it's going and **why** and then it needs some time! :)

**Comment by BillWagner** [comment]
@Meai1 If you haven't seen it yet, you should watch the "Future of C#" build talk by @MadsTorgersen and @DustinCampbell  https://channel9.msdn.com/Events/Build/2016/B889

In it, they discuss where C# is in relationship to other languages in terms of popularity, "most loved" and "most hated" lists. And, they also discuss what is being done to score better on all those surveys.

**Comment by Meai1** [comment]
@BillWagner that video is on topic, i think the tuple stuff is great. more flexibility to write quick and dirty code, now we would just need something like traits / mixins to make the inheritance stuff faster and easier

**Comment by eyalsk** [comment]
@Meai1 Yeah, only traits/mixins require CLR support and we probably wait quite a bit before this will get into the language, unless they are really thinking about it for for C# 8.x but there are other useful things like [extension _everything_](https://github.com/dotnet/roslyn/issues/11159) and record types and immutability so go figure what will end up on the list based on feedback and analysis as well as LDMs.

**Comment by eyalsk** [comment]
@Meai1 You should have posted it on the [C#/Roslyn](https://github.com/dotnet/roslyn/issues) repo and not here.

**Comment by richlander** [comment]
The language rankings are interesting to us, but like anything each ranking is a data-point. There is no project at Microsoft that is focused on achieving a #1 ranking in any one of the language rankings. If C# was at #2 across all of them, we would break out champagne and then take the rest of the week off! ;)

More seriously, I think that C# has an excellent reputation as a language. You should check out the latest blogs posts on this topic by @MadsTorgersen. See:

- https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/
- https://blogs.msdn.microsoft.com/dotnet/2017/02/01/the-net-language-strategy/

Although I'm not part of the C# team or design process, I can tell you that there are two major things that they aim to do:

- Make it easier to build apps that are common/popular/important today.
- Enable similar language features in C# that have proven to be effective in other languages.

I'm personally impressed by the enhancements in C# 7. Unlike C# 6, C# 7 has this flavor that the team is intending to make bold new additions in the future. I'm looking forward to watching what they do. I'm guessing in C# 7 that they finally recovered from the huge Roslyn project! I'm super biased, but I'm proud to be a C# user. 

Also, check out https://github.com/dotnet/csharplang

I hope that answers your question.
