### ISSUE TITLE
Offer tooling to assist with package publishing

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/home#67]
It's probably safe to assume that community is now understood to be the most vital asset of a strong ecosystem.  I've been stoked to see the growth on that front in the .net universe.  The smallest, most tangible unit of measure in my opinion is the package.  You can generally speaking gauge the health of a community by the number of packages it has - even if many of those packages are noise.

For .net, this _has_ existed prior to core, but embracing open source has taken off any limits that might have once existed.

Praises aside however, I think there might be a subtle and important void in the tooling and guidance.  This is something I've observed as I've been trying to automate delivery of a .net package I'm working on.
The current project system flux might have some minor impact on things, but I do believe that even after the dust has settled, some people are going to be frustrated by the process of publishing packages.  Even more specifically: As it pertains to handling the objective of package version.

What's nice is that I recently got a chance to experience how helpful it is when this kind of guidance is offered after getting a typescript project I've authored [prepared as an npm package](http://atrauzzi.blogspot.ca/2016/12/making-typescript-npm-packages.html).
The last challenge I faced was specifically to do with establishing a convention for versioning my releases, tagging a release in github and actually getting the bits to npm.  While researching the topic, I discovered that someone had already recognized this snag and created [a very simple yet crazy-effective tool](https://github.com/semantic-release/semantic-release) to get past this hurdle!

So, be it resolved that packages are important and making package publishing easy is equally as important: I think it would be just awesome if one or more of the various dotnet teams got together offered some kind of formal tooling around package publishing.  Much the same way that semantic-release has done for npm.

**Comment by janvorli** [comment]
cc: @richlander

**Comment by jkotas** [comment]
cc: @karelz

**Comment by richlander** [comment]
Great feedback.

/cc @rrelyea @blackdwarf

**Comment by richlander** [comment]
This is a good suggestion. We don't have any plans to do this currently. It is a good idea. I encourage you or others to make something like the cool project mentioned for .NET. I'm watching the referenced youtube video now.

**Comment by karelz** [comment]
I would actually like to keep this opened. I think this is significant speed bump for growing .NET ecosystem.
We need super-simple packages creation. At minimum in the form of documentation.
While we can ask community to help (e.g. MVPs who have plenty of experience with it), we should IMO keep it on our radar and make it happen rather sooner than later.
Or am I wrong?

cc @terrajobst @danmosemsft @Petermarcu

**Comment by terrajobst** [comment]
> We need super-simple packages creation. 

We already have have that with VS2017:

![image](https://cloud.githubusercontent.com/assets/5169960/25289483/a4d8b666-267e-11e7-9585-8edc4d465b1f.png)

What we don't have is great guidance for library authors that involves all the phases of a project, involving API creation, architecture, strong naming, .NET Standard & cross-targeting, and NuGet. That's something I'm planning to come up with once I have a day where I can breath.
