### ISSUE TITLE
Is dotnet pack still being deprecated?

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/home#68]
Just read in https://github.com/dotnet/cli/issues/2676#issuecomment-214938537 that `dotnet pack` is going to be deprecated.

Is this still the case, or is that now outdated information?

**Comment by atrauzzi** [comment]
@yishaigalatzer - Maybe you can follow up? It's been quite a little bit since that comment was made.

**Comment by mairaw** [comment]
I've confirmed with @blackdwarf and dotnet pack is not being deprecated. 

/cc @piotrpMSFT

**Comment by blackdwarf** [comment]
@atrauzzi `dotnet pack` is not being deprecated and is still alive and well. The comment on that issue, I believe, was concerning the original, pre-preview1 (or was it 2) `dotnet pack` implementation.
