### ISSUE TITLE
New project request

### ISSUE THREAD

**Issue by Kagamine** [dotnet/home#71]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

I want to join .net foundation.

**Comment by jongalloway** [comment]
@Kagamine Great! Please follow the steps to Submit A Project on this page: https://dotnetfoundation.org/get-involved

I'm going to close this issue, you can comment or re-open if you have problems, okay?

**Comment by Kagamine** [comment]
I've already submitted the request, but there was no responses.

**Comment by jongalloway** [comment]
Okay, I see the submission. Sorry for the slow response - I just started in .NET Foundation and am getting caught up on project additions. I'll contact you this coming week to get going, okay?

**Comment by Kagamine** [comment]
ok, My alias is v-yiszhe
