### ISSUE TITLE
The link to check duplicate project names is broken

### ISSUE THREAD

**Issue by jbogard** [dotnet/home#72]
This link:

http://ivantomic.com/projects/ospnc/

404's

See issue:

https://github.com/LogIN-/ospnc/issues/21

**Comment by LogIN-** [comment]
Should work again, I changed servers.. if DNS is finished with propagation you will see it again.

**Comment by svick** [comment]
@LogIN- I'm now getting a prompt for username and password on http://ivantomic.com/projects/ospnc/. Is that expected?

**Comment by jongalloway** [comment]
Site is back up, verified working without login.
