### ISSUE TITLE
Checklist contains invalid hyperlink

### ISSUE THREAD

**Issue by stefanov-stefan** [dotnet/home#73]
The [checklist](https://github.com/dotnet/home/blob/master/guidance/new-projects.md) contains a link to  http://ivantomic.com/projects/ospnc/ which is unreachable.

**Comment by svick** [comment]
This issue is a duplicate of https://github.com/dotnet/home/issues/72.

**Comment by jongalloway** [comment]
Closing as duplicate of #72
